server:
  port: 9663
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_task_manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 204318
# 微信配置
wechat:
  appid: wxd1f424601b29bbf7
  secret: 2b06fcf6e27347bc0e02495d65bf49b7

# JWT 配置
jwt:
  secret: 9a1c3e24b6c1e23cd7e1d8b2e4e8a935b2a9e932f451b9c79ab05f9c3d5f1032
  expire: 86400000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
